name: Java CI with Maven and Tomcat Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          # cache: maven

      - name: Build with Maven
        run: mvn clean package

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Setup SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy WAR to Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TOMCAT_HOST }}
          username: ${{ secrets.TOMCAT_USERNAME }}
          key: ~/.ssh/id_rsa
          script: |
            scp -v -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/web/time-tracker-web-0.5.0-SNAPSHOT.war ec2-user@$
            {{ secrets.TOMCAT_HOST }}:/opt/tomcat/webapps/
              Optional: Enable debug logging for troubleshooting
                env:
                  INPUT_DEBUG: true
