name: Deploy WAR to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy WAR to Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TOMCAT_HOST }}
          username: ${{ secrets.TOMCAT_USERNAME }}
          key: ~/.ssh/id_rsa
          script: |
            scp -v -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/web/time-tracker-web-0.5.0-SNAPSHOT.war ec2-user@${{ secrets.TOMCAT_HOST }}:/opt/tomcat/webapps/
