name: Java CI with Maven and S3 Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
      - name: Debug workspace
        run: |
          ls -la $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE/web/target

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload WAR to S3
        run: |
          aws s3 cp /home/runner/work/GitHub-Action-Power-Cloud/GitHub-Action-Power-Cloud/web/target/*.war s3://your-bucket-name/web/time-tracker-web-0.5.0-SNAPSHOT.war
        env:
          AWS_DEFAULT_REGION: your-region
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
